# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelPackages = pkgs.linuxPackages_latest;

  hardware.enableAllFirmware = true;

  services.upower.enable = true;
  services.power-profiles-daemon.enable = true;

  services.fwupd.enable = true;
  hardware.framework.amd-7040.preventWakeOnAC = true;

  boot.initrd.luks.devices."luks-9e0fd976-102e-4697-95cc-903e91a49672".device = "/dev/disk/by-uuid/9e0fd976-102e-4697-95cc-903e91a49672";

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a84176a1-80da-4b51-8741-eddad59369b6";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-c224e565-5ec5-4a5c-b4a5-f646eb3b6fd4".device = "/dev/disk/by-uuid/c224e565-5ec5-4a5c-b4a5-f646eb3b6fd4";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7A08-C0CE";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/5176a1fb-3ecb-45bb-a569-cffe03fbf604";}
  ];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
